### ISSUE TITLE
Problem with "duplicate key value violates unique constraint"

### ISSUE THREAD

**Issue by riston** [usecanvas/livedb-postgresql#2]
I am using the same setup as it's in readme, on redis as a driver and the postgre for documents and operations. The problem is that when I run two separate copies of Share.js versions which try to insert the same item with same version. 

```
Trace: { [error: duplicate key value violates unique constraint "operations_cname_docname_version"]
  name: 'error',
  length: 276,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (collection_name, document_name, version)=(users, mike, 11945) already exists.',
```

The client side of share looks like this, I am trying to increment single integer from multiple sources and that seems to cause problems.

``` js
    var userDoc = share.get("users", "mike");

    userDoc.subscribe();

    userDoc.whenReady(function () {

        console.log("Snapshot", userDoc.getSnapshot());

        if (!userDoc.type) {
            userDoc.create("json0", { x: 5 });
        }
    });

    var timerRef = window.setInterval(function () {

        userDoc.submitOp([ { p: [ 'x' ], na: 10 }]);
    }, 3000 + ~~(Math.random() * 1000));
```

**Comment by jclem** [comment]
~~Can you explain how it's happening that you're inserting the same version multiple times?~~

Reading the [LiveDB adapter spec](https://github.com/share/livedb/blob/786c5c08ee4837235ebd78748d3fae8e0ba952d9/lib/memory.js) now, apparently `writeOp` can be called multiple times with the same op and version. This method probably needs to use the same "upsert" strategy that `writeSnapshot` is using (rather unfortunately).

Another option might be to just catch E23505 and assume that the duplicate `writeOp` call described in the spec is what happened. I'm not sure how safe it is to do this (cc @nateps?), because this won't tell us if the data in the op that's already been written is identical to the data in the operation currently attempting to write. Not sure if this matters.

**Comment by riston** [comment]
@jclem, yes I already used the upsert for the writeOp, it seems to be working fine. I haven't updated my fork with the SQL file but I will :). There are other issues currently with livedb-pg module which come up with multiple share instances.

**Comment by jclem** [comment]
@riston What are the other issues? I definitely want to address them. I've been running this package without any issues myself.

**Comment by jclem** [comment]
Closed by https://github.com/usecanvas/livedb-postgresql/pull/4.
